//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMobile
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int MaBL { get; set; }
        public string TenNguoiBL { get; set; }
        public string TieuDeBL { get; set; }
        public string NoiDungBL { get; set; }
        public Nullable<System.DateTime> NgayBL { get; set; }
        public Nullable<int> MaSP { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
