//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMobile
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuangCao
    {
        public int MaQC { get; set; }
        public string TenCty { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> Ngaybatdau { get; set; }
        public Nullable<System.DateTime> Ngayhethan { get; set; }
    }
}
