//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMobile
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int MaTin { get; set; }
        public string TieuDe { get; set; }
        public string TomTat { get; set; }
        public string UrlHinh { get; set; }
        public string NoiDung { get; set; }
        public bool AnHien { get; set; }
    }
}
